# This Cloud Build configuration automates building your Docker image
# and deploying it to Cloud Run. This acts as your "MCP Toolbox" for CI/CD.
# This comment is to trigger a new build.

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dorian-engine:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dorian-engine:$COMMIT_SHA']

# Step 3: Deploy the Docker image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'dorian-engine'
    - '--image'
    - 'gcr.io/$PROJECT_ID/dorian-engine:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--set-secrets=/etc/secrets/firebase-admin-sdk-credentials.json=firebase-admin-sdk-credentials:latest'
    - '--update-secrets=FIREBASE_API_KEY=FIREBASE_API_KEY:latest,FIREBASE_AUTH_DOMAIN=FIREBASE_AUTH_DOMAIN:latest,FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest,FIREBASE_STORAGE_BUCKET=FIREBASE_STORAGE_BUCKET:latest,FIREBASE_MESSAGING_SENDER_ID=FIREBASE_MESSAGING_SENDER_ID:latest,FIREBASE_APP_ID=FIREBASE_APP_ID:latest,FIREBASE_MEASUREMENT_ID=FIREBASE_MEASUREMENT_ID:latest'
  env:
    - 'PROJECT_ID=$PROJECT_ID'

options:
  logging: CLOUD_LOGGING_ONLY
